apps:
  pages:
    - number: 1
      items:
        - App Store
        - Mail
        - Contacts
        - Calendar
        - Reminders
        - Notes
        - FaceTime
        - folder: Docs
          pages:
            - number: 1
              items:
                - Numbers
                - Pages
                - Keynote
        - folder: Productivity
          pages:
            - number: 1
              items:
                - Obsidian
                - Todoist
                - Linear
                - ChatGPT
                - Claude
                - Perplexity
                - Folo
                - Figma
                - WebCatalog
        - Messages
        - Maps
        - Find My
        - Photos
        - Voice Memos
        - Weather
        - Books
        - Clock
        - Home
        - System Settings
        - folder: Other
          pages:
            - number: 1
              items:
                - Shortcuts
                - Time Machine
        - folder: Others
          pages:
            - number: 1
              items:
                - Activity Monitor
                - Disk Utility
                - Font Book
                - Dictionary
                - Calculator
                - Stickies
                - Grapher
                - Mission Control
                - VoiceOver Utility
                - AirPort Utility
                - System Information
                - Console
                - Automator
                - Script Editor
                - Digital Color Meter
                - ColorSync Utility
                - Screenshot
                - Audio MIDI Setup
                - Bluetooth File Exchange
                - Screen Sharing
                - TextEdit
                - Print Center
                - Feedback Assistant
                - Terminal
                - Tips
                - Stocks
                - Migration Assistant
                - Chess
                - Photo Booth
                - Preview
                - Image Capture
                - QuickTime Player
        - folder: Developer
          pages:
            - number: 1
              items:
                - Visual Studio Code
                - IntelliJ IDEA Ultimate
                - DataGrip
                - PhpStorm
                - Android Studio
                - Xcode
                - Termius
                - GitKraken
                - Postman
                - Local
                - Ghostty
                - Docker
                - OpenLens
        - folder: Utilities
          pages:
            - number: 1
              items:
                - Bitwarden
                - Pearcleaner
                - Raycast
                - Latest
                - JetBrains Toolbox
                - AltTab
                - Hidden Bar
        - folder: Browsers
          pages:
            - number: 1
              items:
                - Chromium
                - LibreWolf
                - Safari
        - folder: Medias
          pages:
            - number: 1
              items:
                - IINA
                - Podcasts
                - TV
                - Music
        - folder: Other
          pages:
            - number: 1
              items:
                - Passwords
                - iPhone Mirroring
                - Image Playground
                - Freeform
                - Siri
        - folder: Social
          pages:
            - number: 1
              items:
                - Telegram
                - Discord
                - Slack
                - WhatsApp
                - X
        - Microsoft Word
        - Udemy
widgets:
  pages: []
dock_items:
  apps:
    - /System/Applications/Launchpad.app
    - /System/Applications/Calendar.app
    - /System/Applications/Mail.app
    - /Applications/Todoist.app
    - /Applications/Folo.app
    - /Applications/Linear.app
    - /Applications/Slack.app
    - /Applications/Discord.app
    - /Applications/Obsidian.app
    - /Applications/Ghostty.app
    - /Applications/Chromium.app
    - /System/Volumes/Preboot/Cryptexes/App/System/Applications/Safari.app
    - /Applications/ChatGPT.app
    - /Applications/Claude.app
    - /Applications/Visual Studio Code.app
    - /Users/wilfriedago/Applications/IntelliJ IDEA Ultimate.app
    - /Users/wilfriedago/Applications/DataGrip.app
    - /Applications/GitKraken.app
    - /Applications/Postman.app
    - /Applications/Figma.app
  settings:
    autohide: true
    largesize: 91
    magnification: true
    minimize-to-application: true
    mru-spaces: false
    show-recents: false
    tilesize: 31
desktop: {}
