"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false # Add do not need this extra line

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[battery]
disabled = true # I can keep my eyes on the battery level by my own

# [shell]
# zsh_indicator = "󰊠"
# style = "green bold"
# disabled = false

# [status]
# symbol = " "
# success_symbol = ""
# not_executable_symbol = " "
# map_symbol = false
# disabled = false

[directory]
read_only = " "
truncation_length = 4
format = '[$path ]($style)'
truncation_symbol = '…/'
truncate_to_repo = false

# [memory_usage]
# symbol = "󰍛 "
# disabled = true

[hostname]
ssh_only = true
ssh_symbol = " "

[aws]
symbol = "󰸏 "
force_display = false

[azure]
symbol = " "
disabled = false

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = "󰡨 "

[dotnet]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[erlang]
symbol = " "

[gcloud]
symbol = " "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = "󰊢 "
tag_disabled = false

[git_metrics]
ignore_submodules = true
disabled = true

[golang]
symbol = " "

[gleam]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[kubernetes]
symbol = "󱃾 "
disabled = false

[lua]
symbol = "󰢱 "

[meson]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = "󱄅 "

[nodejs]
symbol = "󰎙 "

[openstack]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
style = "green bold"

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = " "

[terraform]
symbol = "󱁢 "
