"$schema" = 'https://starship.rs/config-schema.json'

# Don't print a newline at the start of the prompt
add_newline = false

command_timeout = 2000

format = """
$os\
$username\
$directory\
$git_branch\
$git_commit\
$git_status\
$git_metrics\
$git_state\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$package\
$docker_context\
$kubernetes\
$shell\
$container\
$jobs\
${custom.memory_usage}\
${custom.battery}\
${custom.keyboard_layout}\
$time\
$cmd_duration\
$status\
$line_break\
$character\
"""

palette = 'default'

[palettes.default]

color_ok = 'bright-green'
color_danger = 'bright-red'
color_caution = 'bright-yellow'

color_os = 'red'
color_username = 'red'
color_directory = 'yellow'
color_git = 'cyan'
color_git_added = 'bright-green'
color_git_deleted = 'bright-red'
color_env = 'blue'
color_kubernetes = 'purple'
color_docker = 'blue'
color_shell = ''
color_container = ''
color_other = ''
color_time = ''
color_duration = ''

color_vimcmd_ok = 'green'
color_vimcmd_replace = 'purple'
color_vimcmd_visual = 'yellow'

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[os]
disabled = true
style = "fg:color_os"
format = '[$symbol]($style)'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = false
style_user = "fg:color_username"
style_root = "bold fg:color_danger"
format = '[ $user ]($style)'

[battery]
disabled = true # I can keep my eyes on the battery level by my own

[time]
disabled = true # I find this kinda useless
time_format = "%R"
format = '[󰔛 $time ]($style)'

[cmd_duration]
min_time = 2000
format = '[took 󱫑 $duration ]($style)'
show_milliseconds = false
disabled = false

[git_branch]
symbol = " "
only_attached = true
ignore_branches = []
truncation_length = 25
truncation_symbol = "..."
always_show_remote = false
disabled = false

[git_status]
format = '[($ahead_behind )($all_status )]($style)'
stashed = "*${count}"
ahead = "⇡${count}"
behind = "⇣${count}"
up_to_date = ""
diverged = "⇡${ahead_count}⇣${behind_count}"
conflicted = "=${count}"
deleted = "×${count}"
renamed = "»${count}"
modified = "!${count}"
staged = "+${count}"
untracked = "?${count}"
ignore_submodules = false
disabled = false

[git_metrics]
format = '[(([+$added]($added_style))([-$deleted]($deleted_style)) )](fg:color_git)'
added_style = "fg:color_git_added"
deleted_style = "fg:color_git_deleted"
only_nonzero_diffs = true
disabled = true

[git_state]
format = '[($state( $progress_current/$progress_total) )]($style bold)'
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
disabled = false

# [shell]
# zsh_indicator = "󰊠"
# style = "green bold"
# disabled = false

# [status]
# symbol = " "
# success_symbol = ""
# not_executable_symbol = " "
# map_symbol = false
# disabled = false

[directory]
read_only = " "
truncation_length = 4
format = '[$path ]($style)'
truncate_to_repo = false

# [memory_usage]
# symbol = "󰍛 "
# disabled = true

[hostname]
ssh_only = true
ssh_symbol = " "

[aws]
symbol = "󰸏 "
disabled = true
force_display = false

[azure]
symbol = " "
disabled = false

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = "󰡨 "

[dotnet]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[erlang]
symbol = " "

[gcloud]
symbol = " "

[golang]
symbol = " "

[gleam]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[kubernetes]
symbol = "󱃾 "
disabled = false

[lua]
symbol = "󰢱 "

[meson]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = "󱄅 "

[nodejs]
symbol = "󰎙 "

[openstack]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
style = "green bold"

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = " "

[terraform]
symbol = "󱁢 "
