config:
  backup: false
  banner: false
  create: true
  dotpath: ~/.dotfiles
  keepdot: true
  link_dotfile_default: nolink
  link_on_import: nolink
profiles:
  default:
    dotfiles:
    - f_zshrc
    - f_zshenv
    - f_starship
    - d_aerospace
    - d_fabric
    - d_fzf
    - d_lazydocker
    - d_lazygit
    - d_neofetch
    - d_nvim
    - d_zsh
    - d_warp
    - d_scripts
  macos:
    dotfiles:
    - f_vscode_settings

dotfiles:
  f_zshrc:
    src: .zshrc
    dst: ~/.zshrc
  f_zshenv:
    src: .zshenv
    dst: ~/.zshenv
  f_starship:
    src: .config/starship.toml
    dst: ~/.config/starship.toml
  d_aerospace:
    src: .config/aerospace
    dst: ~/.config/aerospace
  d_fabric:
    src: .config/fabric
    dst: ~/.config/fabric
  d_fzf:
    src: .config/fzf
    dst: ~/.config/fzf
  d_lazydocker:
    src: .config/lazydocker
    dst: ~/.config/lazydocker
  d_lazygit:
    src: .config/lazygit
    dst: ~/.config/lazygit
  d_neofetch:
    src: .config/neofetch
    dst: ~/.config/neofetch
  d_nvim:
    src: .config/nvim
    dst: ~/.config/nvim
  d_zsh:
    src: .config/zsh
    dst: ~/.config/zsh
  d_warp:
    src: .warp
    dst: ~/.warp
  d_scripts:
    src: .scripts
    dst: ~/.scripts
  f_vscode_settings:
    src: .vscode/settings.jsonc
    dst: ~/Library/Application Support/Code/User/settings.json
