config:
  backup: true
  banner: false
  create: true
  dotpath: ~/.dotfiles
  keepdot: true
  link_dotfile_default: nolink
  link_on_import: nolink
profiles:
  default:
    dotfiles:
    - f_zshrc
    - f_zshenv
    - d_config
    - d_warp
    - d_scripts
  macos:
    dotfiles:
    - f_vscode_settings

dotfiles:
  f_zshrc:
    src: .zshrc
    dst: ~/.zshrc
  f_zshenv:
    src: .zshenv
    dst: ~/.zshenv
  d_config:
    src: .config
    dst: ~/.config
  d_warp:
    src: .warp
    dst: ~/.warp
  d_scripts:
    src: .scripts
    dst: ~/.scripts
  f_vscode_settings:
    src: .vscode.settings.jsonc
    dst: ~/Library/Application Support/Code/User/settings.json
