config:
  backup: true
  banner: false
  create: true
  dotpath: ~/.dotfiles
  keepdot: true
  link_dotfile_default: nolink
  link_on_import: nolink
profiles:
  default:
    dotfiles:
    - f_zshrc
    - f_zshenv
    - d_config
    - d_shell
    - d_warp
    - d_neofetch
  macos:
    dotfiles:
    - f_vscode

dotfiles:
  f_zshrc:
    src: .zshrc
    dst: ~/.zshrc
  f_zshenv:
    src: .zshenv
    dst: ~/.zshenv
  d_config:
    src: .config
    dst: ~/.config
  d_shell:
    src: .shell
    dst: ~/.shell
  d_warp:
    src: .warp
    dst: ~/.warp
  d_neofetch:
    src: .config/neofetch
    dst: ~/.config/neofetch
  f_vscode:
    src: .vscode/settings.json
    dst: ~/Library/Application Support/Code/User/settings.json
