config:
  backup: true
  banner: false
  create: true
  dotpath: ~/.dotfiles
  keepdot: true
  link_dotfile_default: nolink
  link_on_import: nolink
profiles:
  default:
    dotfiles:
    - d_shell
    - f_vscode
    - f_zshrc
    - f_zshenv
    - d_warp
dotfiles:
  d_shell:
    src: .shell
    dst: ~/.shell
  f_zshrc:
    src: .zshrc
    dst: ~/.zshrc
  f_vscode:
    src: .vscode/settings.json
    dst: ~/Library/Application Support/Code/User/settings.json
  f_zshenv:
    src: .zshenv
    dst: ~/.zshenv
  d_warp:
    src: .warp
    dst: ~/.warp
