config:
  backup: false
  banner: false
  create: true
  dotpath: ~/.dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
profiles:
  default:
    dotfiles:
    - d_aerospace
    - f_colima.yaml
    - d_fabric
    - d_gh
    - d_lazydocker
    - d_lazygit
    - d_neofetch
    - d_nvim
    - d_zsh
    - f_starship
    - f_zshenv
    - f_zshrc
    - d_scripts
    - d_warp
  macos:
    dotfiles:
    - f_vscode

dotfiles:
  d_aerospace:
    src: config/aerospace
    dst: ~/.config/aerospace
  f_colima.yaml:
    src: config/colima/default/colima.yaml
    dst: ~/.config/colima/default/colima.yaml
  d_fabric:
    src: config/fabric
    dst: ~/.config/fabric
  d_gh:
    src: config/gh
    dst: ~/.config/gh
  d_lazydocker:
    src: config/lazydocker
    dst: ~/.config/lazydocker
  d_lazygit:
    src: config/lazygit
    dst: ~/.config/lazygit
  d_neofetch:
    src: config/neofetch
    dst: ~/.config/neofetch
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_zsh:
    src: config/zsh
    dst: ~/.config/zsh
  f_starship:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  d_scripts:
    src: scripts
    dst: ~/.scripts
  d_warp:
    src: warp
    dst: ~/.warp
  f_vscode:
    src: vscode/settings.json
    dst: ~/Library/Application Support/Code/User/settings.json
