config:
  backup: false
  banner: false
  create: true
  dotpath: ~/.dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
profiles:
  default:
    dotfiles:
    - d_aerospace
    - d_fabric
    - d_gh
    - d_gh-copilot
    - d_lazydocker
    - d_lazygit
    - d_neofetch
    - d_nvim
    - d_starship
    - d_zsh
    - f_zprofile
    - f_zshenv
    - f_zshrc
    - d_scripts
    - d_warp
    - f_yazi.toml
    - d_zed
  macos:
    dotfiles:
    - f_vscode_settings
    - f_vscode_keybindings
    - d_vscode_snippets

dotfiles:
  d_aerospace:
    src: config/aerospace
    dst: ~/.config/aerospace
  d_fabric:
    src: config/fabric
    dst: ~/.config/fabric
  d_gh:
    src: config/gh
    dst: ~/.config/gh
  d_gh-copilot:
    src: config/gh-copilot
    dst: ~/.config/gh-copilot
  d_lazydocker:
    src: config/lazydocker
    dst: ~/.config/lazydocker
  d_lazygit:
    src: config/lazygit
    dst: ~/.config/lazygit
  d_neofetch:
    src: config/neofetch
    dst: ~/.config/neofetch
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_starship:
    src: config/starship
    dst: ~/.config/starship
  d_zsh:
    src: config/zsh
    dst: ~/.config/zsh
  f_zprofile:
    src: .zprofile
    dst: ~/.zprofile
  f_zshenv:
    src: .zshenv
    dst: ~/.zshenv
  f_zshrc:
    src: .zshrc
    dst: ~/.zshrc
  d_scripts:
    src: scripts
    dst: ~/.scripts
  d_warp:
    src: warp
    dst: ~/.warp
  f_vscode_settings:
    src: vscode/settings.json
    dst: ~/Library/Application Support/Code/User/settings.json
  f_vscode_keybindings:
    src: vscode/keybindings.json
    dst: ~/Library/Application Support/Code/User/keybindings.json
  d_vscode_snippets:
    src: vscode/snippets
    dst: ~/Library/Application Support/Code/User/snippets
  f_yazi.toml:
    src: config/yazi/yazi.toml
    dst: ~/.config/yazi/yazi.toml
  d_zed:
    src: config/zed
    dst: ~/.config/zed

