config:
  backup: false
  banner: false
  create: true
  dotpath: ~/.dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
profiles:
  default:
    dotfiles:
      - f_aerospace
      - d_fabric
      - d_gh
      - f_gh-copilot
      - f_lazydocker
      - f_lazygit
      - f_neofetch
      - d_nvim
      - d_zsh
      - f_starship
      - f_zprofile
      - f_zshenv
      - f_zshrc
      - d_scripts
      - f_yazi.toml
      - d_gitkraken_themes
  macos:
    dotfiles:
      - f_vscode_settings
      - f_vscode_keybindings
      - d_vscode_snippets

dotfiles:
  f_aerospace:
    src: config/aerospace.toml
    dst: ~/.config/aerospace/aerospace.toml
  d_fabric:
    src: config/fabric
    dst: ~/.config/fabric
  d_gh:
    src: config/gh
    dst: ~/.config/gh
  f_gh-copilot:
    src: config/gh-copilot.yml
    dst: ~/.config/gh-copilot/config.yml
  f_lazydocker:
    src: config/lazydocker.yml
    dst: ~/.config/lazydocker/config.yml
  f_lazygit:
    src: config/lazygit.yml
    dst: ~/.config/lazygit/config.yml
  f_neofetch:
    src: config/neofetch.conf
    dst: ~/.config/neofetch/config.conf
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_starship:
    src: config/starship.toml
    dst: ~/.config/starship/starship.toml
  d_zsh:
    src: config/zsh
    dst: ~/.config/zsh
  f_zprofile:
    src: .zprofile
    dst: ~/.zprofile
  f_zshenv:
    src: .zshenv
    dst: ~/.zshenv
  f_zshrc:
    src: .zshrc
    dst: ~/.zshrc
  d_scripts:
    src: scripts
    dst: ~/.scripts
  f_vscode_settings:
    src: config/vscode/settings.json
    dst: ~/Library/Application Support/Code/User/settings.json
  f_vscode_keybindings:
    src: config/vscode/keybindings.json
    dst: ~/Library/Application Support/Code/User/keybindings.json
  d_vscode_snippets:
    src: config/vscode/snippets
    dst: ~/Library/Application Support/Code/User/snippets
  f_yazi.toml:
    src: config/yazi.toml
    dst: ~/.config/yazi/yazi.toml
  d_gitkraken_themes:
    src: config/gitkraken/themes
    dst: ~/.gitkraken/themes
