# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

gui:
  showBottomLine: false
  border: rounded
  nerdFontsVersion: "3"

  spinner:
    #? NOTE: https://stackoverflow.com/questions/2685435/cooler-ascii-spinners
    frames:
      - "\U0001F311"
      - "\U0001F312"
      - "\U0001F313"
      - "\U0001F314"
      - "\U0001F315"
      - "\U0001F316"
      - "\U0001F317"
      - "\U0001F318"
    rate: 80

customCommands:
  - key: "C"
    command: "cz"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"

  - key: 'n'
    context: 'localBranches'
    prompts:
      - type: 'menu'
        title: 'What kind of branch is it?'
        key: 'BranchType'
        options:
          - name: 'feature'
            description: 'a feature branch'
            value: 'feature'
          - name: 'hotfix'
            description: 'a hotfix branch'
            value: 'hotfix'
          - name: 'release'
            description: 'a release branch'
            value: 'release'
      - type: 'input'
        title: 'What is the new branch name?'
        key: 'BranchName'
        initialValue: ''
    command: "git flow {{.Form.BranchType}} start {{.Form.BranchName}}"
    loadingText: 'Creating branch'
