# This file is sourced at the start of a login shell session.

# Homebrew initialization
if [[ -f "/opt/homebrew/bin/brew" ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# eliminates duplicates in *paths
typeset -gU cdpath fpath path
