"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false # Add do not need  this extra line

[character]
success_symbol = '[➜](bold green)' # This rememmber me Robby Russel's Oh My Zsh theme
error_symbol = "[➜](bold red)"

[battery]
disabled = true # I can keep my eyes on the battery level from the menu bar, no thanks
